# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: godmode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'godmode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgodmode.proto\x12\x07godmode\"0\n\x14\x44\x65\x63omposeTaskRequest\x12\x18\n\x10task_description\x18\x01 \x01(\t\"\xbe\x01\n\x15\x44\x65\x63omposeTaskResponse\x12\x15\n\roriginal_task\x18\x01 \x01(\t\x12\x12\n\ncomplexity\x18\x02 \x01(\t\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x05\x12>\n\x16\x65xtracted_requirements\x18\x04 \x01(\x0b\x32\x1e.godmode.ExtractedRequirements\x12\"\n\x08subtasks\x18\x05 \x03(\x0b\x32\x10.godmode.Subtask\"T\n\x15\x45xtractedRequirements\x12\x14\n\x0ctechnologies\x18\x01 \x03(\t\x12\x10\n\x08patterns\x18\x02 \x03(\t\x12\x13\n\x0b\x63onstraints\x18\x03 \x03(\t\"\xa1\x01\n\x07Subtask\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncomplexity\x18\x03 \x01(\t\x12\x16\n\x0e\x61ssigned_agent\x18\x04 \x01(\t\x12\x18\n\x10\x61gent_confidence\x18\x05 \x01(\x02\x12\x17\n\x0f\x61gent_reasoning\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x07 \x03(\t2b\n\x0eGodModeService\x12P\n\rDecomposeTask\x12\x1d.godmode.DecomposeTaskRequest\x1a\x1e.godmode.DecomposeTaskResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'godmode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECOMPOSETASKREQUEST']._serialized_start=26
  _globals['_DECOMPOSETASKREQUEST']._serialized_end=74
  _globals['_DECOMPOSETASKRESPONSE']._serialized_start=77
  _globals['_DECOMPOSETASKRESPONSE']._serialized_end=267
  _globals['_EXTRACTEDREQUIREMENTS']._serialized_start=269
  _globals['_EXTRACTEDREQUIREMENTS']._serialized_end=353
  _globals['_SUBTASK']._serialized_start=356
  _globals['_SUBTASK']._serialized_end=517
  _globals['_GODMODESERVICE']._serialized_start=519
  _globals['_GODMODESERVICE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
