apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>-deployment
  labels:
    app: <APP_NAME>
spec:
  replicas: <REPLICA_COUNT>
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
      - name: <APP_NAME>
        image: <IMAGE_NAME>
        ports:
        - containerPort: <CONTAINER_PORT>
---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>-service
spec:
  selector:
    app: <APP_NAME>
  ports:
    - protocol: TCP
      port: <SERVICE_PORT>
      targetPort: <CONTAINER_PORT>
  type: LoadBalancer
